### ISSUE TITLE
SUGGESION : Improvements in user's api response time by handling the data syncing/ initial set up part independently via mongodb change streams.

### ISSUE THREAD

**Issue by arizworld** [hiteshchoudhary/apihub#51]
Hii, I would like to point out some improvements on how we are syncing the data between the different modules on user creation/update. 

**Reference:**

![Screenshot (8)](https://github.com/hiteshchoudhary/apihub/assets/60315087/0913ba95-22b6-45fd-ba48-e05ad6fdec49)

**Problem:**
The way we are doing it now it works fine, but it is affecting the user's api response time, as the user have to wait for all the queries to be executed in the post save hook. Besides by using the post save hook we're limiting the scope of using serveral methods such as update , findoneandupdate. see below image. 

![image](https://github.com/hiteshchoudhary/apihub/assets/60315087/d8b09768-89b3-44a3-b4d6-5bc52f0f12fc)

**Suggestion :** 

I think we can achieve the simillar result by using [Mongodb Change Streams](https://www.mongodb.com/docs/manual/changeStreams/). Basically when a change in user collection occurs we can listen for it and do the same data syncing part independently. Thus improving the response time of user's api. And I also believe it will be a better example to the people who will study from this codebase.

**Setup Problem** 

As change streams needs a [replica sets](https://www.mongodb.com/docs/manual/replication/) or [sharded](https://www.mongodb.com/docs/manual/sharding/) clusters to work. To setup the server locally the contributors will need to have the same. Which can be tough to set up. To handle this we can choose to use the current solution or mongodb change streams based on the Node Env.

**Note:**
If this suggestion seems reasonable let me know I'll love to contribute on this part. And also a huge round of applause to @hiteshchoudhary for providing us with this repository, you have been a huge inspiration throughout my growing phase as a developer.

**Comment by wajeshubham** [comment]
Hi @arizworld,

Thank you for taking the time to provide us with your insights and suggestions. We genuinely appreciate your interest in improving the project.

Regarding the issue you raised about data syncing between different modules on user creation/update, we understand your concern about the impact on API response time. Your suggestion to implement **MongoDB Change Streams** is indeed intriguing and could lead to better performance. 

However, we designed this project with learners in mind, and we aimed to keep the setup process as simple and straightforward as possible. **_We're aware that setting up replica sets or sharded clusters can be challenging, especially for newcomers. That's why we initially chose the current solution to avoid complicating the learning experience._**

We're open to further discussion on this matter. While we may not implement the change immediately due to our commitment to a learner-friendly environment and issue not being a severe one but, we're interested in exploring options to make advanced features like **MongoDB Change Streams** more accessible to contributors in the future. 

Your willingness to contribute in this area is fantastic, and **we'd like to take this conversation forward to be clear and on the same page before we proceed with the PR**.

Once again, thank you for your valuable input and for being a part of our community. If you have any more suggestions or questions, please don't hesitate to share them.

Best regards,
FreeAPI team

**Comment by arizworld** [comment]
Hi @wajeshubham thanks for taking my suggestion into consideration. I appreciate your concern about the learner-friendly environment. I hope this suggestion provide a whole another perspective to our learning friends out there. Thanks!

**Comment by wajeshubham** [comment]
Keeping the suggestions in the loop but closing this issue as not planned. Thanks for the contribution @arizworld
