### ISSUE TITLE
authorization token 

### ISSUE THREAD

**Issue by DKdev117** [hiteshchoudhary/apihub#53]
no option is avaliable in the Swagger UI authorization token

**Comment by wajeshubham** [comment]
Hi @DKdev117 ,

Thank you for bringing up this concern regarding the Swagger UI. In our project, we have opted for a cookie-based authentication approach, which might differ from the more common method of using bearer tokens.

Here's how our authentication process works:

1. **User Registration/Login:** To access any protected route within the swagger apis, developers are required to first register or log in. Upon successful authentication, the server sets a cookie in the user's browser that contains an authentication token.

2. **Automatic Token Handling:** The browser automatically includes this token in every subsequent request made to the backend. This eliminates the need for users to manually add an authentication token to their requests, simplifying the process.

3. **Swagger UI Purpose:** In FreeAPI inclusion of the Swagger UI primarily serves as a tool for exploring and testing our API endpoints. It allows users to interact with our API, view responses, and perform testing without the need to manage authentication tokens themselves.

4. **Postman Collection:** We are also actively working on a Postman collection for our entire application. This collection is well-documented and provides an option to pass a bearer token for authenticated requests. While it's still in development, we plan to roll out comprehensive Postman documentation soon to cater to users who prefer using bearer tokens for API testing and want to explore it in postman instead of swagger.

We hope this clarifies our approach to authentication and its interaction with Swagger UI. If you have any more questions or need further assistance, please feel free to ask.

Best regards,
FreeAPI team

**Comment by DKdev117** [comment]
I am understand what is you talk about but my question is how to enable Bear Authorization Token in Swagger for the all Routes you need you set token.

**Comment by wajeshubham** [comment]
@DKdev117 We need to specify the security scheme  in the `swagger.yml` file either globally or for each endpoint (we are having secure and public routes so to add a security scheme globally doesn't make sense in our application). We avoided this cumbersome step to allow developers seamlessly test and preview the api responses by following the cookie-based authentication. 

If you want to know how to enable bearer authentication you can follow this official blog: https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by DKdev117** [comment]
@wajeshubham thank you
