### ISSUE TITLE
Refactor: Refrain from Immediate Invocation of Middleware Functions in Route Definitions

### ISSUE THREAD

**Issue by talhariaz324** [hiteshchoudhary/apihub#64]
In the file located at /src/routes, a subtle issue has been identified regarding the usage of middleware functions in route definitions. The middleware function, such as userForgotPasswordValidator, is being invoked with parentheses, potentially leading to unexpected behavior. It is recommended to pass middleware functions as references without immediate invocation, aligning with best practices.

Steps to Reproduce:
1- Navigate to /src/routes.
2- Inspect the specific route definitions.
3- Observe that middleware functions like userForgotPasswordValidator are invoked with parentheses.

Expected Result:
Middleware functions should ideally be passed as references without immediate invocation when defining routes to ensure proper execution during the request-response cycle. As per the Express.js documentation: **Middleware are functions that have access
to the request object (req), the response object (res), and the next middleware function in the application’s request-response cycle.**

Express.js Documentation: https://expressjs.com/en/guide/writing-middleware.html#:~:text=Middleware%20functions%20are%20functions%20that,middleware%20succeeding%20the%20current%20middleware

![Screenshot from 2024-01-03 23-17-10](https://github.com/hiteshchoudhary/apihub/assets/75393543/5b66bca4-d3fe-4845-bd9c-bc2457e164ed)

Actual Result:
The middleware functions are invoked with parentheses during route definition.
![Screenshot from 2024-01-03 23-31-34](https://github.com/hiteshchoudhary/apihub/assets/75393543/a6b811c8-a1ca-44f3-8baa-bb3a7c9acb4d)

Middleware functions often rely on dynamic behavior based on the request context, such as extracting data from the request object. When invoked immediately, these functions may not have access to the request object and may not behave as expected and  Invoking the middleware immediately may skip the error-handling logic during route definition.

Relevant Context:
This observation is made within the context of Express.js routing. Invoking middleware functions with parentheses during route definition, even for seemingly small issues, can potentially lead to unforeseen challenges, as middleware functions are designed to execute dynamically during the request-response cycle.

Actual Example:
```javascript
router
  .route("/forgot-password")
  .post(userForgotPasswordValidator(), validate, forgotPasswordRequest);
``` 

Expected Example:
```javascript
router
  .route("/forgot-password")
  .post(userForgotPasswordValidator, validate, forgotPasswordRequest);
``` 

Contributor's Note:
I am interested in addressing this issue and plan to work on a solution. I would appreciate any feedback or additional guidance from maintainers and the community as I proceed with the resolution.

**Comment by wajeshubham** [comment]
Hi @talhariaz324,

Thank you for bringing up this concern and sharing your observations on the usage of middleware functions in our route definitions. I understand the importance of maintaining best practices for code readability and functionality.

I've reviewed your observations and wanted to provide some clarification regarding the use of middleware functions in our Express.js routes. Specifically, I noticed you pointed out the usage of middleware functions like `userForgotPasswordValidator()` and expressed concern about their immediate invocation during route definition.

In our implementation, the middleware functions, such as `userForgotPasswordValidator()`, are designed to return the validation chain provided by the Express Validator library. This pattern is consistent with the recommended usage outlined in the Express Validator documentation.

As you've rightly mentioned, Express Validator allows for the creation of reusable validation chains, and in our case, the middleware functions act as generators for these chains. 

This approach helps us **keep our code modular, clean, and easy to maintain**. The validation chain itself is an array of middleware functions, and invoking it immediately during route definition is intentional and aligns with the library's design.

Here's a practical example from the Express Validator documentation that demonstrates a similar usage pattern:

```javascript
const createEmailChain = () => body('email').isEmail();
app.post('/login', createEmailChain(), handleLoginRoute);
app.post('/signup', createEmailChain().custom(checkEmailNotInUse), handleSignupRoute);
```

As you can see, the `createEmailChain()` function is invoked immediately, and the returned validation chain is used as middleware in the route definitions. Our usage pattern is consistent with this approach, and it allows us to encapsulate the validation logic within reusable functions.

If you have any further questions or concerns, please feel free to discuss them. Closing this issue for now!

Best regards,
FreeAPI team

**Comment by talhariaz324** [comment]
Hi @wajeshubham,

Thank you for the prompt and detailed response. I appreciate the clarification on the intentional design choice regarding the immediate invocation of middleware functions to generate reusable validation chains. Your explanation, along with the example from the Express Validator documentation, provides a clear understanding of your approach and how it aligns with best practices.

I understand the importance of maintaining code modularity, cleanliness, and following library design principles. It's reassuring to know that the usage pattern is intentional and contributes to the overall maintainability of the codebase.

I appreciate the transparency and the effort you've put into explaining the rationale behind the current implementation. If there are no further concerns or questions, I'll consider this matter addressed and will respect the decision to close the issue.

Thank you again for your time and guidance.

Best regards,
Talha
