### ISSUE TITLE
CORS issue after my own deployment on Railway [ Vue JS ]

### ISSUE THREAD

**Issue by hafizjavaid** [hiteshchoudhary/apihub#76]
### Describe the bug

My application was successfully deployed and I got the following URL

https://freeapi-app-production-a55c.up.railway.app/

I'm trying to fetch the todos by following link

https://freeapi-app-production-a55c.up.railway.app/api/v1/todos

But it is giving me corse issue

Just to be clear I'm using Vue js on frontend side ( Vite Template )

### Screenshots

Error Screenshot
![image](https://github.com/hiteshchoudhary/apihub/assets/49143414/0250307c-f5dd-4196-b65b-1c1f6ab0fd1a)

Code:

![image](https://github.com/hiteshchoudhary/apihub/assets/49143414/1026b8ca-3a1d-46dd-acb8-a959f07b1f26)

### Additional context or Information

I'm not used to open source pardon me please if I made any mistake 

Thank you

**Comment by shrey-dadhaniya** [comment]
Hi @hafizjavaid,
please check your variables in railway make sure you have **CORS_ORIGIN** set to *****.
if you don't find then please add CORS_ORIGIN=\*
and restart server. I don't have paid plan for railway  otherwise i will share you more screenshots 

![image](https://github.com/hiteshchoudhary/apihub/assets/50957657/7134b716-fb53-4eba-9dda-25e802a282da)

**Comment by hafizjavaid** [comment]
Hi @shrey-dadhaniya 

Thank you for your help. It's working now

Best wishes,
Hafiz
